### ISSUE TITLE
Only up and down thrust works on Android.

### ISSUE THREAD

**Issue by pirogronian** [ArneSchwettmann/ArnesSpaceTaxi#1]
Just tested v20 on Android. 3 upper touch fields runs up thrust, 3 bottom runs down thrust, middle does nothing.

Sorry for spamming email, I was confused by github mobile interface.

**Comment by rsn8887** [comment]
You have to thrust to launch the taxi up. Then when in the air, press the touch field to retract landing gear. Once landing gear is retracted you can thrust in all directions. It is a game mechanic of space taxi :) when landing gear is down you can only go up/down.

**Comment by pirogronian** [comment]
Good to know, thanks :)

**Comment by ArneSchwettmann** [comment]
You have to retract your landing gear after taking off. It is a game mechanic of Space Taxi. When your landing gear is down, you can not go sideways. Once you are in the air, press the other touch field to retract your landing gear. Once landing gear is retracted you can thrust in all directions. :)
